### PR TITLE
Feature swashbuckle2 2

### PR DESCRIPTION
**Pull request by ginkzul**
Hi, @frandi . This is another option I've got.
In this one, I modified the BaseController's method from `public override` to `protected`.
And I have to modify the all the child class endpoint that previously override the BaseController's from `public override` to `public new`.

Take example from the `FacilityController`, I modified:

- `public override ActionResult<FacilityDto> Get(int id)` to 
  `public new ActionResult<FacilityDto> Get(int id)`

- `public override ActionResult<FacilityDto> Put(int id, [FromBody] EditFacilityDto value)` to 
  `public new ActionResult<FacilityDto> Put(int id, [FromBody] EditFacilityDto value)`

- `public override IActionResult Delete(int id)` to 
  `public new IActionResult Delete(int id)`

There is no need for modification in the method's body.

I think, this option comply your two notes before:

- Controller doesn't have to implement anything unless it is needed with the requirement

- BaseController was created to help controllers in implementing common methods to prevent repeated logics. So it shouldn't control controller's behavior.

But, how do you think about this one?

### CODE REVIEW

**Comment by frandi** [comment]
Hi @ginkzul awesome, that's close to what I wanted it.

Some more improvements though:
1. I'd want to remove the `virtual` completely from the base methods. Because the child controller will always call `base.[method]` for the implementation. If it needs different implementation they can just create another methods and use it without calling the `base`. What do you say?

2. Swagger is really a documentation where user can examine it to understand an API. As a user, I might still not fully understand about an endpoint by just seeing the url path and its payload. I need some descriptive comments about what it does, what are the parameters, what exceptions that might occur when I use the operation, etc. And also, `Delete` should return `201`, not `200`, shouldn't it? Can you do something to make the swagger to be more descriptive?

You might want to check this https://petstore.swagger.io/ to understand what I mean.

**Comment by ginkzul** [comment]
Hi, @frandi 

1. Completely agree with that. Will remove it right away. 

2. Yes. Now that I am sure about which direction to take, I will continue working with the Swagger documentation. I'll take a look at the example. Thank you for the guidance.

**Comment by ginkzul** [comment]
Hi @frandi , very sorry for taking too long.
I've updated my commit.
I removed the `virtual` keyword from BaseController.
Then, I added XML Comments to the Controllers to make the Swagger Documentation more help full.
Kindly check if it's okay with you.

**Review by frandi — CHANGES_REQUESTED** [review]
Awesome, thanks @ginkzul, i think it's enough. A little fix before I merge this PR though, could you please revert the changes you made on `appsettings.json`?

**Comment by ginkzul** [comment]
Sorry @frandi , forgot to change it back before commit.
I've revert it back now.

**Comment by frandi** [comment]
Thanks @ginkzul 👍

**Pull request closed without merging**
